name: api_utils
description: A package to handle API requests for gRPC or REST
version: 0.0.1-dev08+0
homepage: "https://github.com/quabynah-bilson/api_utils"
publish_to: "none"

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.2.6 <5.0.0'

dependencies:
  flutter:
    sdk: flutter
  grpc: ^3.2.3
  dio: ^5.2.1+1
  logger: ^1.4.0
  dartz: ^0.10.1
  retrofit: ^4.0.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
